name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14 version
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Install, test
        run: |
          yarn
          yarn test
        env:
          CI: true
